### ISSUE TITLE
Multi-language support？

### ISSUE THREAD

**Issue by shyu216** [Crayon-ShinChan/mr-resume#6]
Hi, I like your project, but I am wondering if you plan to make the resume support multiple languages or not.

like a switch between English and Chinese

i tried to do so in my resume, but the code looks ugly in the end

**Comment by mengxi-ream** [comment]
Hi Shyu, thank you for your request.

In our future plans, I have taken into consideration the support for internationalization (i18n). I am considering using [next-intl](https://next-intl-docs.vercel.app/)  to achieve this and allow for multiple versions of the resume to be deployed together.

However, this feature will not be integrated into the current main branch due to the following reasons:
1. The main branch is currently in a feature-frozen state and will undergo significant changes in future versions.
2. next-intl is currently on beta for server components, so I prefer to wait for their 3.0 release.

If you really require internationalization now, you can refer to the next-intl documentation or the [official documentation](https://nextjs.org/docs/app/building-your-application/routing/internationalization) on internationalization in Next.js.

**Comment by mengxi-ream** [comment]
Btw, I noticed that for our project, when we switch languages from English to Chinese, the length of the content changes, requiring us to adjust the CSS, such as the line height, for each resume. We may need to find a convenient solution for this.

**Comment by shyu216** [comment]
thanks for your answer， let me close it
